### ISSUE TITLE
Aligning the wrists, head and pelvis

### ISSUE THREAD

**Issue by ijorquera** [YadiraF/PIXIE#13]
Hello, I have been doing a few tests with pixie (using body as the type) to obtain the pose of the smplx given a picture and I managed to get the joints rotation from param_dict['body'] after applying some conversions, but when I try to use those values on a regular smplx in blender or unity I end up with a misalign between the wrists, the pelvis (global_pose) and the head, for example the body is looking backwards while the head is looking to the cam and the wrist are all over the place.

The fingers and the body parts seems to be fine when compared to the picture except for the other 3 parts, so I wanted to know if there is a right way to obtain the joints rotation while keeping the 3 bodies aligned or if there is a known way to easily align them.

Thanks.

**Comment by ijorquera** [comment]
Welp, the solution to my problem was in the decoder function in pixie.

**Comment by ujjawalcse** [comment]
Hey @ijorquera ,
Me too trying the same thing.
Can you please share your script here ?
Thanks.

**Comment by ujjawalcse** [comment]
@ijorquera , Please suggest how you did that. Which are the things you are referring to in the `decode function` of `pixie.py`

**Comment by raflitp** [comment]
Hi are you able to import pixie output into blender ?? Did you change it into fbx or bvh too ??
