### ISSUE TITLE
FileNotFoundError - smplx_extra_joints.yaml

### ISSUE THREAD

**Issue by woo1** [YadiraF/PIXIE#2]
> total 12 images
> creating the SMPLX Decoder
> Traceback (most recent call last):
>   File "demos/demo_fit_body.py", line 165, in <module>
>     main(parser.parse_args())
>   File "demos/demo_fit_body.py", line 35, in main
>     pixie = PIXIE(config = pixie_cfg, device=device)
>   File "/Projects/PIXIE/pixielib/pixie.py", line 50, in __init__
>     self._create_model()
>   File "/Projects/PIXIE/pixielib/pixie.py", line 108, in _create_model
>     self.smplx = SMPLX(self.cfg.model).to(self.device)
>   File "/Projects/PIXIE/pixielib/models/SMPLX.py", line 157, in __init__
>     fname=config.extra_joint_path)
>   File "/Projects/PIXIE/pixielib/models/lbs.py", line 398, in __init__
>     with open(fname, 'r') as f:
> FileNotFoundError: [Errno 2] No such file or directory: '/Projects/PIXIE/data/smplx_extra_joints.yaml'

Thanks for sharing this code. 
When I try these commands, the error appears
But there is no 'smplx_extra_joints.yaml' in [smpl-x](https://smpl-x.is.tue.mpg.de/download.php) site
`
python demos/demo_fit_body.py --saveObj True 
`
`
python demos/demo_animate_body.py 
`

How can I get the file?

**Comment by sreeharshaparuchur1** [comment]
Hey, may I know where you found the yaml file in question?

**Comment by woo1** [comment]
@sreeharshaparuchur1 
https://github.com/YadiraF/PIXIE/blob/master/Doc/docs/getting_started.md
PIXIE_DATA
you can download it in this link

**Comment by bewithme** [comment]
> > total 12 images
> > creating the SMPLX Decoder
> > Traceback (most recent call last):
> > File "demos/demo_fit_body.py", line 165, in 
> > main(parser.parse_args())
> > File "demos/demo_fit_body.py", line 35, in main
> > pixie = PIXIE(config = pixie_cfg, device=device)
> > File "/Projects/PIXIE/pixielib/pixie.py", line 50, in **init**
> > self._create_model()
> > File "/Projects/PIXIE/pixielib/pixie.py", line 108, in _create_model
> > self.smplx = SMPLX(self.cfg.model).to(self.device)
> > File "/Projects/PIXIE/pixielib/models/SMPLX.py", line 157, in **init**
> > fname=config.extra_joint_path)
> > File "/Projects/PIXIE/pixielib/models/lbs.py", line 398, in **init**
> > with open(fname, 'r') as f:
> > FileNotFoundError: [Errno 2] No such file or directory: '/Projects/PIXIE/data/smplx_extra_joints.yaml'
> 
> Thanks for sharing this code. When I try these commands, the error appears But there is no 'smplx_extra_joints.yaml' in [smpl-x](https://smpl-x.is.tue.mpg.de/download.php) site `python demos/demo_fit_body.py --saveObj True ` `python demos/demo_animate_body.py `
> 
> How can I get the file?

I have the same problem, how do you fix it ?
