### ISSUE TITLE
How to get T-Pose body mesh with face details and texture

### ISSUE THREAD

**Issue by ujjawalcse** [YadiraF/PIXIE#25]
Hey,
Congrats for this great work.
I tested this repository and glad to see the results.
Can anyone suggest me how to get T-Pose body mesh with texture details (along with DECA's facial texture and details) ?
Thanks.

**Comment by ujjawalcse** [comment]
Got it.

**Comment by Shreeshail-Hingane** [comment]
Hi @ujjawalcse,
I want to do the same. Could you please mention how you were able to add texture details?
Thanks in advance.

**Comment by ujjawalcse** [comment]
Hey @Shreeshail-Hingane ,
Just change the lines after 100 like this,
if args.saveObj:
           # visualizer.save_obj(os.path.join(savefolder, name, f'{name}.obj'), opdict)
            
            if 'Tpose_vertices' not in opdict.keys():
                 opdict['Tpose_vertices'] = pixie.decode_Tpose(codedict)
            visualizer.save_obj(os.path.join(savefolder, name, f'{name}.obj'), opdict,Tpose=True)

Thanks
