### ISSUE TITLE
FLAME_albedo_from_BFM.npz not found

### ISSUE THREAD

**Issue by smithee77** [YadiraF/PIXIE#4]
Hi, first congrats for your work :)

I'm running your code in Colab and getting this error:

!python demos/demo_fit_face.py --saveObj True 

**FileNotFoundError: [Errno 2] No such file or directory: '/content/PIXIE/data/FLAME_albedo_from_BFM.npz'**

Any clue? Should I download this file from any website?
Thanks a lot

**Comment by jjandnn** [comment]
教程中写着：https://github.com/TimoBolkart/BFM_to_FLAME

**Comment by saurabhmahra91** [comment]
I am getting the same error. How did you resolve this?
