### ISSUE TITLE
OSError: Failed to interpret file '/home/michael/PIXIE/data/SMPLX_NEUTRAL_2020.npz' as a pickle

### ISSUE THREAD

**Issue by Michaelwhite34** [YadiraF/PIXIE#44]
python demos/demo_fit_body.py --saveObj True 

total 12 images
creating the SMPLX Decoder
Traceback (most recent call last):
  File "/home/michael/anaconda3/envs/pixie-env/lib/python3.7/site-packages/numpy/lib/npyio.py", line 448, in load
    return pickle.load(fid, **pickle_kwargs)
_pickle.UnpicklingError: invalid load key, 'E'.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "demos/demo_fit_body.py", line 165, in <module>
    main(parser.parse_args())
  File "demos/demo_fit_body.py", line 35, in main
    pixie = PIXIE(config = pixie_cfg, device=device)
  File "/home/michael/PIXIE/pixielib/pixie.py", line 50, in __init__
    self._create_model()
  File "/home/michael/PIXIE/pixielib/pixie.py", line 108, in _create_model
    self.smplx = SMPLX(self.cfg.model).to(self.device)
  File "/home/michael/PIXIE/pixielib/models/SMPLX.py", line 113, in __init__
    ss = np.load(config.smplx_model_path, allow_pickle=True)
  File "/home/michael/anaconda3/envs/pixie-env/lib/python3.7/site-packages/numpy/lib/npyio.py", line 451, in load
    "Failed to interpret file %s as a pickle" % repr(file)) from e
OSError: Failed to interpret file '/home/michael/PIXIE/data/SMPLX_NEUTRAL_2020.npz' as a pickle

**Comment by pfeducode** [comment]
> python demos/demo_fit_body.py --saveObj True
> 
> total 12 images creating the SMPLX Decoder Traceback (most recent call last): File "/home/michael/anaconda3/envs/pixie-env/lib/python3.7/site-packages/numpy/lib/npyio.py", line 448, in load return pickle.load(fid, **pickle_kwargs) _pickle.UnpicklingError: invalid load key, 'E'.
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last): File "demos/demo_fit_body.py", line 165, in main(parser.parse_args()) File "demos/demo_fit_body.py", line 35, in main pixie = PIXIE(config = pixie_cfg, device=device) File "/home/michael/PIXIE/pixielib/pixie.py", line 50, in **init** self._create_model() File "/home/michael/PIXIE/pixielib/pixie.py", line 108, in _create_model self.smplx = SMPLX(self.cfg.model).to(self.device) File "/home/michael/PIXIE/pixielib/models/SMPLX.py", line 113, in **init** ss = np.load(config.smplx_model_path, allow_pickle=True) File "/home/michael/anaconda3/envs/pixie-env/lib/python3.7/site-packages/numpy/lib/npyio.py", line 451, in load "Failed to interpret file %s as a pickle" % repr(file)) from e OSError: Failed to interpret file '/home/michael/PIXIE/data/SMPLX_NEUTRAL_2020.npz' as a pickle

Have you solved this problem? I  got the same one
