### ISSUE TITLE
   File "/home/pfrobot/anaconda3/envs/pixie-env/lib/python3.7/site-packages/numpy/lib/npyio.py", line 451, in load     "Failed to interpret file %s as a pickle" % repr(file)) from e OSError: Failed to interpret file 'PIXIE-master/data/SMPLX_NEUTRAL_2020.npz' as a pickle

### ISSUE THREAD

**Issue by pfeducode** [YadiraF/PIXIE#47]
I have a problem ,can you give me some proposals

![2022-10-14_14-09](https://user-images.githubusercontent.com/100210045/195775287-762616c5-d470-4ec9-b85c-b716c26b992f.png)

**Comment by Ironieser** [comment]
Hi, have you solved this problem?  How did you solve it? Thx.

**Comment by Ironieser** [comment]
> Hi, have you solved this problem? How did you solve it? Thx.↳

I fixed this by re-downloading the file, SMPLX_NEUTRAL_2020.npz, from the URL: https://download.is.tue.mpg.de/download.php?domain=smplx&sfile=SMPLX_NEUTRAL_2020.npz

THX.

**Comment by pfeducode** [comment]
> > 你好，你解决了这个问题吗？你是怎么解决的？谢谢↳
> 
> 我通过从 URL 重新下载文件 SMPLX_NEUTRAL_2020.npz 来修复此问题：[https://download.is.tue.mpg.de/download.php ?domain=smplx&sfile=SMPLX_NEUTRAL_2020.npz](https://download.is.tue.mpg.de/download.php?domain=smplx&sfile=SMPLX_NEUTRAL_2020.npz)
> 
> 谢谢。

Thank you for your answer. Because there are too many messages, I ignored your question. At present, I am mainly testing the ddfm model. Thank you for solving this problem. I will continue to focus on this warehouse and start the next step of research.
