### ISSUE TITLE
No such file or directory: '/content/PIXIE/data/FLAME_albedo_from_BFM.npz

### ISSUE THREAD

**Issue by smithee77** [YadiraF/PIXIE#5]
Hi, first congrats for your work :)

I'm running your code in Colab and getting this error:

!python demos/demo_fit_face.py --saveObj True

**FileNotFoundError: [Errno 2] No such file or directory: '/content/PIXIE/data/FLAME_albedo_from_BFM.npz'**

In the instruction says that ALBEDO stuff is optional. I'm getting this error with all demo scripts. Any clue? 
Is it compulsory to install albedo repo?

Thanks a lot

**Comment by ErickTurro** [comment]
Same here: at the beginning, I was also getting this error because I read in the instructions that albedo was optional. Anyway if you clone the albedo repo and follow the instructions to get that .npz file, it should solve this issue.

**Comment by lovegihubdd** [comment]
In the parameters put --useTex false  --lightTex false

**Comment by jinfagang** [comment]
demo_animate_body.py: error: unrecognized arguments: --lightTex false @lovegihubdd

**Comment by saisriteja** [comment]
@smithee77  I am wondering if you have a working code that can run in colab. If so can anyone share that link?

**Comment by smithee77** [comment]
@saisriteja hi, sorry I deleted old stuff months ago. Anyway, I solved my issue downloading the file (FLAME_albedo_from_BFM.npz) to Drive folder, and copying in the folder . /content/PIXIE/data/ in each execution. Hope that helps
